name = "QuadJGK"
uuid = "f27e79a0-bbaa-47b5-b2d3-8db3cef8b089"
authors = ["lxvm <lorenzo@vanmunoz.com>"]
version = "0.1.0"

[compat]
AutoBZCore = "0.3"
DataStructures = "0.18"
HypergeometricFunctions = "0.3"
QuadGK = "2"
julia = "1.9"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[extensions]
QuadJGKAutoBZCoreExt = "AutoBZCore"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[weakdeps]
AutoBZCore = "66bd3e16-1600-45cf-8f55-0b550710682b"